### ISSUE TITLE
Unable to resolve the request "adldap/login".

### ISSUE THREAD

**Issue by joshkennedy** [thepitagroup/adldap_craftcms#1]
Hey @thepitagroup - _really_ glad for your hard work on this plugin. We're trying to get it to work in our organization for a little micro-site. I'm not sure why, but I keep getting the error: `Unable to resolve the request "adldap/login".` I'm also noticing that the plugin isn't saving the Craft User Group handle. 

I followed the readme, have a Pro version of Craft, and a user group set up. 

Any ideas? Thanks in advance!

**Comment by thepitagroup** [comment]
Thanks  @joshkennedy   for your feedback. 

There was a couple issues that I resolved and commited back. That should fix the issue with the group not displaying on the back end, and maybe other ssues w.  

For the resolve request issue, 

1. make sure that in you /config/general.php you have the 
,'loginPath'=>'login'
 ,'postLoginRedirect' => ''

like in this example 

```
'*'=>array(
        'omitScriptNameInUrls' => true,
        'maxUploadFileSize' => 268435456,
        'defaultTemplateExtensions' => array('twig')
        ,'loginPath'=>'login'
        ,'postLoginRedirect' => ''
    ),
```

2. make sure that the page that you want to password protect behind LDAP has this 

```
{% requireLogin %}
{% if currentUser.isInGroup("WhateverTheGroupHandleYouHavePickedInYourSettings") %} //With matching closing {% endif %}
```

3. and last but not least in the login page which unless modified in the loginPath abaove should be at the root of your template and should contain this:
//CUSTOMIZE TO WHAT YOU NEED  DID NOT PUT LABEL 
 ```
<form method="post" accept-charset="UTF-8">
    {{ getCsrfInput() }}
    <input type="hidden" name="action" value="adldap/login">
    <input type="hidden" name="redirect" value="{{redirect}}">
 <input id="username" type="text" name="username" value="{{ craft.session.rememberedUsername }}">
    <input id="password" type="password" name="password">

</form>

```

**Comment by jeraldjuice** [comment]
Hi, @thepitagroup , I think that the issue that @joshkennedy is referencing comes from the fact that the "AdldapControllers.php" file in the "controllers" folder should actually be named "AdldapController.php". That fixed the route not being recognized for me.

**Comment by chrdavid** [comment]
I can confirm that. After renaming "AdldapControllers.php" to "AdldapController.php" it works.

**Comment by thepitagroup** [comment]
@joshkennedy , @chrdavid Thank you both for pointing the problem. The controller name has been updated.
